# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DK's github pages
email: denka.peng@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
 据说github的gh-pages被墙掉了，好吧，我只是看下，如果你看到了这个页面，那么请继续点击进入一篇文章，不能访问就真的是被墙掉了。。。
 任何吐槽和建议请发送至邮箱。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.acfun.tv" # the base hostname & protocol for your site
twitter_username: cobantou
github_username:  cobantou

# Build settings
markdown: kramdown
